from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('wayz-iotkit', src, depend = ['PKG_USING_WAYZ_IOTKIT'], CPPPATH = CPPPATH)

Return('group')
